main:
  - name: Bio
    url: '/#about'
    weight: 10
  - name: Research
    url: '/#research'
    weight: 20
  - name: Teaching
    url: '/#teaching' # Aggiunto: link alla sezione Teaching sulla Home
    weight: 30
  - name: Experience
    url: '/experience/'
    weight: 35
  - name: Policy
    url: '/#policy'
    weight: 40
  - name: Other
    url: '/#other'
    weight: 50
  - name: CV
    url: '/uploads/resume.pdf'
    weight: 60
