main:
  - name: Bio
    url: '/#about'
    weight: 10
  - name: Research
    url: '/#research'
    weight: 20
  - name: Policy
    url: '/#policy'
    weight: 30
  - name: Experience
    url: '/experience/'
    weight: 40
  - name: Other
    url: '/other/'
    weight: 50
  - name: CV
    url: '/uploads/resume.pdf'
    weight: 60
