main:
  - name: Bio
    url: '/'
    params:
      fragment: 'about'
    weight: 10

  - name: Research
    url: '/'
    params:
      fragment: 'research'
    weight: 20

  - name: Policy
    url: '/'
    params:
      fragment: 'policy'
    weight: 40

  - name: Experience
    url: '/experience/'
    weight: 35

  - name: Other
    url: '/'
    params:
      fragment: 'other'
    weight: 50

  - name: CV
    url: '/uploads/resume.pdf'
    weight: 60
