main:
  - name: Bio
    url: '#about'
    weight: 10
  - name: Research
    url: '#projects'
    weight: 20
  - name: Teaching
    url: '#experience' # Questo link porter√† all'inizio della sezione Experience sulla Home
    weight: 30
  - name: Experience
    url: '/experience/' # Link alla pagina dedicata
    weight: 35
  - name: Policy
    url: '#policy'
    weight: 40
  - name: Other
    url: '#other'
    weight: 50
  - name: CV
    url: uploads/resume.pdf
    weight: 60
