# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#   desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: '#about' # L'ID standard per il widget Biografia
    weight: 10
  - name: Research
    url: '#projects' # Linka al widget Progetti/Ricerca
    weight: 20
  - name: Teaching
    url: '#experience' # Linka al widget Esperienza/Didattica
    weight: 30
  - name: Policy
    url: '#policy' # Anchor per la sezione Policy (da creare)
    weight: 40
  - name: Other
    url: '#other' # Anchor per la sezione Hobbies/Altro (da creare)
    weight: 50
  - name: CV
    url: uploads/resume.pdf # Link diretto al file PDF (non scorre)
    weight: 60
