main:
  - name: Bio
    url: '#about'
    weight: 10

  - name: Research
    url: '#research'
    weight: 20

  - name: Teaching
    url: '#teaching'
    weight: 30

  - name: Policy
    url: '#policy'
    weight: 40

  - name: Other
    url: '#other'
    weight: 50

  - name: CV
    url: '/uploads/resume.pdf'
    weight: 60
