main:
  - name: Bio
    url: '#about'
    weight: 10
  - name: Research
    url: '#research' # Nuovo Anchor
    weight: 20
  - name: Teaching
    url: '#teaching' # Nuovo Anchor
    weight: 30
  - name: Policy
    url: '#policy' # Nuovo Anchor
    weight: 40
  - name: Other
    url: '#other' # Nuovo Anchor
    weight: 50
  - name: CV
    url: uploads/resume.pdf
    weight: 60
