# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: teal

  # ðŸ‘‰ Add your custom CSS file here
  custom_css:
    - css/custom.css

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'PhD Student in Economics at the University of Zurich, specializing in behavioral and labor economics and gender inequalities.'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: "7hcGu2_Ht0po1PXFyc4bEZvqrU70DPcaRrwZI6yZXlo"
    baidu: ''

# Sezione AGGIUNTA per caricare le icone Font Awesome (fas)
icon:
  pack: fas # Imposta Font Awesome Solid come pacchetto di icone principale
  pack_brands: fab # Carica Font Awesome Brands (per icone social)
  pack_academic: ai # Carica Academicons (per icone Google Scholar/ORCID)
# Fine Sezione Aggiunta

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    logo:
      text: 'Sara Rabino'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
